# Generated by Django 4.0.4 on 2022-05-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Текст кнопки', max_length=40)),
                ('link', models.CharField(blank=True, default=None, help_text='Ссылка', max_length=2048, null=True)),
                ('number', models.IntegerField(blank=True, help_text='Порядковы номер кнопки в сообщении (от 1 до 10)', null=True)),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст сообщения', null=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(help_text='id пользователя', primary_key=True, serialize=False, verbose_name='id')),
                ('is_bot', models.BooleanField(default=False, help_text='Бот?')),
                ('first_name', models.CharField(blank=True, default=None, help_text='Имя пользователя telegram', max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, default=None, help_text='Фамилия пользователя telegram', max_length=64, null=True)),
                ('username', models.CharField(blank=True, default=None, help_text='Имя пользователя (с @) telegram', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('button', models.ForeignKey(blank=True, default=None, help_text='Кнопка, являющаяся триггером', null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.button')),
                ('message', models.ForeignKey(blank=True, default=None, help_text='Сообщение, являющаяся триггером', null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.message')),
                ('next_message', models.ForeignKey(blank=True, default=None, help_text='Сообщение, которое будет отправлено при срабатывание триггера', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextMessage', to='constructor.message')),
            ],
            options={
                'verbose_name': 'Триггер',
                'verbose_name_plural': 'Триггеры',
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=None)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('reply_markup', models.JSONField(blank=True, default=None, null=True)),
                ('photos', models.JSONField(blank=True, default=None, null=True)),
                ('json', models.JSONField(blank=True, default=None, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='constructor.telegramuser')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='constructor.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('calldata', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=None)),
                ('message', models.JSONField(blank=True, default=None, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_to', to='constructor.telegramuser')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_from', to='constructor.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='button',
            name='message',
            field=models.ForeignKey(help_text='Сообщение, к которому принадлежит кнопка', on_delete=django.db.models.deletion.CASCADE, to='constructor.message'),
        ),
    ]
